### PR TITLE
Add external cover images

### PR DESCRIPTION
**Pull request by coliveiraeti**
Allows using an image hosted on a different domain as cover image.

_I use a CDN to store my images, thus I made these changes so I can use it as the source of Bludit's cover images._

### CODE REVIEW

**Comment by acrox999** [comment]
I second this idea. I've always wanted this feature anyway. :+1:

**Comment by acrox999** [comment]
@coliveiraeti Can you update this? We should try to convince @dignajar again to have this into Bludit. :P

**Comment by dignajar** [comment]
I added this feature on Bludit v2, when you create a page, on the advanced tab there is a field for put the uRL.

**Comment by dignajar** [comment]
Implemented on Bludit v2.

**Pull request closed without merging**
