### PR TITLE
Category descriptions

### PR DESCRIPTION
**Pull request by JonathanHolvey**
Add descriptions to categories via the manage categories admin page, and access them in themes via the `$Page` global object. PR changes consist of:

- Change `dbList::edit()` to allow any property via an array
- Add method `dbList::getProperty()` to access saved properties, and edit `dbList::getName()` to use it
- Change `editCategory()` function to include a description parameter
- Add input field to edit category view and controller scripts
- Add method `Page::categoryDescription()` for access in themes

### CODE REVIEW

**Comment by dignajar** [comment]
Hi,
I don't see the point to add a description to a category, I saw it in other CMS, but I never use it.
The idea to add `properties` or extra fields for dblist class I like it, I going to considerate to add it.
Thanks

**Comment by JonathanHolvey** [comment]
Hi,

Having a category description is useful when displaying a list of categories. It allows for providing considerably more information than the category name alone. This fills out the content visually, and gives the reader a better idea about what each category contains.

I'm using this in a new Bludit site at the moment, and, while I can get an image from the posts within each category, there's no way I can generate meaningful text without the CMS having it stored in the category database.

This change would add very little weight to Bludit, and I believe it could be very useful when used in more complex themes.

Cheers,
Jon

**Comment by JonathanHolvey** [comment]
Is there any chance this feature could be included in Bludit? I'm using it now at http://heirloom-earth.com, and this PR has received a couple of thumbs-ups. Still working correctly with the latest `master`.

**Comment by Turqueso** [comment]
I agree with @JonathanHolvey that it can be very useful while remaining optional

**Comment by JonathanHolvey** [comment]
If I update this PR so the conflicts are resolved, is there any chance of it being included?

**Comment by dignajar** [comment]
I created an issue about it, I'm still not sure about this change. https://github.com/bludit/bludit/issues/732

**Pull request closed without merging**
