### PR TITLE
Fix disable user option

### PR DESCRIPTION
**Pull request by anaggh**
https://github.com/bludit/bludit/issues/683

### CODE REVIEW

**Comment by dignajar** [comment]
I think this is not the fix for the https://forum.bludit.org/viewtopic.php?f=6&t=1146

Also, this is not necessary, the user can put the password `!` and in the database is going to be encrypted with a long hash and is going to be different than `!`.

**Comment by anaggh** [comment]
https://github.com/bludit/bludit/blob/master/bl-kernel/dbusers.class.php#L30-L36 This attempts to fix `disableUser()` since `dbUsers->set()` converts it to hash instead of '!' and `$User->enabled()`. broke.

Also less than 6 characters cannot be set by default. `define('PASSWORD_LENGTH', 6);` 

Closing this.

**Comment by dignajar** [comment]
I get it, you are right.
Why you close the Pull request?

**Comment by anaggh** [comment]
Sorry, I thought you were implementing a different solution

**Comment by dignajar** [comment]
No, I do not check for another solution, but looks like is not clear my code because I check it my self and I don't understand :P

**Pull request merged**
