### PR TITLE
Update frontend dependencies

### PR DESCRIPTION
**Pull request by anaggh**

### CODE REVIEW

**Comment by dignajar** [comment]
Thank you, have did some test ? there are a lot of dependencies changes :D

**Comment by anaggh** [comment]
Yup, tested manually. Everything seemed to work fine.

**Comment by anaggh** [comment]
Also there is now another tiny mce update 5.3.0 -> 5.3.1 

https://www.tiny.cloud/docs/changelog/
```
Version 5.3.1 May 27, 2020

    fixed the image upload error alert also incorrectly closing the image dialog.
    fixed editor content scrolling incorrectly on focus in Firefox by reverting default content CSS html and body heights added in 5.3.0.

```

**Comment by anaggh** [comment]
I wrote a tiny bash script for tinymce bludit updates - https://github.com/anaggh/bludit-scripts/blob/master/tinymce-prepare/prepare-tinymce-plugin.sh Let me know if it is correct.

**Pull request merged**
