### PR TITLE
Add .webp support and fix #1467 

### LINKED ISSUE #1467: Webp image upload doesn't work on shared hosting.
Uploading a **webp** image does not work on some shared hosts due to `symlink` restrictions (this function is in `bl-kernel/functions.php` on line 892).

**Bludit 3.14.1**

### PR DESCRIPTION
**Pull request by gaincoder**

### CODE REVIEW

**Comment by gaincoder** [comment]
fix #1467

**Review by dignajar — COMMENTED** [review]
Hi, it's really hard to review this code is like you remove all and add all the code , so the changes are not visible.

**Comment by carlosmintfan** [comment]
> Hi, it's really hard to review this code is like you remove all and add all the code , so the changes are not visible.

Hi @dignajar, are you using Linux? You should be able to install `meld` under debian. So far I saw, tabs were converted to spaces and 
```php
		switch($extension)
		{
			case '.jpg':
			case '.jpeg':
				$img = imagecreatefromjpeg($file);
				break;
			case '.gif':
				$img = imagecreatefromgif($file);
				break;
			case '.png':
				$img = imagecreatefrompng($file);
				break;
			default:
				$img = false;
				break;
		}
		return $img;
	}
```
was changed to
```php
        switch($extension)
        {
            case '.jpg':
            case '.jpeg':
                $img = imagecreatefromjpeg($file);
                break;
            case '.gif':
                $img = imagecreatefromgif($file);
                break;
            case '.png':
                $img = imagecreatefrompng($file);
                break;
            case '.webp':
                $img = imagecreatefromwebp($file);
                break;
            default:
                $img = false;
                break;
        }
        return $img;
    }
```
adding the webp case.
Okay, something more.
I'd recommend you installing meld and comparing the following to files. The first is the original one, but with tabs converted to four spaces using python. The second is the new one. Hope I helped you by this! :)
(Using .txt because github doesn't support uploading a php here)
[one.txt](https://github.com/bludit/bludit/files/13941757/one.txt)
[two.txt](https://github.com/bludit/bludit/files/13941758/two.txt)
A patch:
[patch.txt](https://github.com/bludit/bludit/files/13941791/patch.txt)

**Comment by gaincoder** [comment]
Sorry for that, was done by my IDE automatically. But you can tell GitHub to ignore Whitespace Changes:
image

**Pull request merged**
