### PR TITLE
Create de_AT.json

### PR DESCRIPTION
**Pull request by SamBrishes**
Hellow,

I was very surprised that there is a `de_CH` version but no `de_AT` translation! I know, it isn't really necessary, but I still had to do such a translation. Sorry.

### The changes compared to de_DE / de_CH:
```
de_DE - "January": "Januar",
de_AT - "January": "Jänner",

de_DE - "you-do-not-have-sufficient-permissions": "Keine Berechtigung, die Seite aufzurufen.",
de_AT - "you-do-not-have-sufficient-permissions": "Keine Berechtigung, diese Seite aufzurufen.",

de_DE - "click-here-to-cancel": "Schliessen",
de_AT - "click-here-to-cancel": "Schließen",

de_DE - "drag-and-drop-to-sort-the-plugins": "Die Reihenfolge der Plugings kann mit Drag and Drop geändert werden.",
de_AT - "drag-and-drop-to-sort-the-plugins": "Die Reihenfolge der Plugins kann per Drag and Drop geändert werden.",

de_DE - "upload": "Upload",
de_AT - "upload": "Hochladen",

de_DE - "the-content-is-saved-as-a-draft-to-publish-it": "Der Inhalt ist als Entwurf gespeichert. Um ihn zu veröffentlichen, klicke <b>Veröffentlichen<\/b>, wenn du ihn du weiter daran arbeiten möchtest, klicke <b>Als Entwurf speichern<\/b>.",
de_AT - "the-content-is-saved-as-a-draft-to-publish-it": "Der Inhalt ist als Entwurf gespeichert. Um ihn zu veröffentlichen, klicke <b>Veröffentlichen<\/b>, wenn du ihn weiter bearbeiten möchtest, klicke <b>Als Entwurf speichern<\/b>.",

de_DE - "site": "Website",
de_AT - "site": "Seite",

de_DE - "first": "Anfang",
de_AT - "first": "Erste",

de_DE - "last": "Ende",
de_AT - "last": "Letzte",

de_DE - "there-are-no-pages-at-this-moment": "Es gibt keine Seiten.",
de_AT - "there-are-no-pages-at-this-moment": "Es gibt noch keine Seiten.",

de_DE - "there-are-no-static-pages-at-this-moment": "Es gibt keine statischen Inhalte.",
de_AT - "there-are-no-static-pages-at-this-moment": "Es gibt noch keine statischen Inhalte.",

de_DE - "there-are-no-draft-pages-at-this-moment": "Es gibt keine Entwürfe."
de_DE - "there-are-no-draft-pages-at-this-moment": "Es gibt noch keine Entwürfe.",

de_DE - "this-plugin-depends-on-the-following-plugins": "Um dieses Plugin zu verwenden, braucht es auch folgendes Plugin:",
de_AT - "this-plugin-depends-on-the-following-plugins": "Dieses Plugin benötigt die folgenden Plugins:",

de_DE - "system-updated": "Das System wurde aufdatiert",
de_AT - "system-updated": "Das System wurde aktualisiert",
```

Sincerely,
Sam.

### CODE REVIEW

**Comment by philippd1** [comment]
I agree to every translation (except the one below) + think they should also be the de_DE value

translations that should be changed imo
- "drag-and-drop-to-sort-the-plugins": "Die Reihenfolge der Plugins kann per Drag and Drop geändert werden."

**Comment by SamBrishes** [comment]
Thanks, that's true. I'll change it

**Comment by SamBrishes** [comment]
Fixed

**Comment by philippd1** [comment]
👍
well, so I'm basically approving this PR, let's wait for @dignajar  to merge this one :)

**Comment by philippd1** [comment]
Great work y'all :)

**Pull request merged**
