### PR TITLE
Update ru lang

### PR DESCRIPTION
**Pull request by hide-me**
Added some strings of translation. 
Fixed many grammatical errors. The concept of "content" has been replaced by a more organic and simple word for a Russian person.
Also I deleted non existed site by first translator, and add info about me.

### CODE REVIEW

**Comment by dignajar** [comment]
Hi,
if you don';t mind I going to add the previus guys who translate the first time.

Can you help me ? checking the changes in the dictionary. @xm74 @vorons 

Thank you for the transaltions.

Regards
Diego

**Comment by xm74** [comment]
Yes, please.

**Comment by dignajar** [comment]
Thank you everyone.

@hide-me, I need to do some changes in the webserver to provide support for russian language, so give me a few days, I'm talking about the translations for the Landing page, themes and plugins sites.

**Comment by hide-me** [comment]
Ok, no problem. I will try translate plugins (themes alredy).

**Pull request merged**
