### PR TITLE
[WIP] Admin user's username made selectable while installation.

### PR DESCRIPTION
**Pull request by hubbyist**
It is working. But I may miss some side effects so tagged as "[WIP]".

### CODE REVIEW

**Comment by dignajar** [comment]
Hi,
I'm not going to introduce any change on the version v1.x, only security fixes.
I going to implement for the version v2.x with an environment variable.

**Comment by hubbyist** [comment]
I thought about adding an "owner" role to system but seemed far fetched. But if you think that this is more suitable I can try to implement this for v2 branch.

**Comment by dignajar** [comment]
This PR is deprecated with the current master branch.
The user admin is necesarry, you can create a new Administrator and disable the user admin for security reasons.

**Comment by hubbyist** [comment]
what are these extra commits showing up in this branch?

**Pull request closed without merging**
