### PR TITLE
Update Parsedown 1.7.4 -> 1.8.0-beta-7

### PR DESCRIPTION
**Pull request by hxii**
This will allow ParsedownExtra to work as well.

### CODE REVIEW

**Comment by dignajar** [comment]
Hi, I don't like the idea to add a beta version.

Otherwise, ParasedownExtra exists as a plugin. https://github.com/bludit-plugins/parsedown-extra probably needs some updates.

**Comment by hxii** [comment]
@dignajar You've got a point, even though the beta at this point looks like stable code.

**Comment by dignajar** [comment]
Hi, are you going to update the plugin ?

**Comment by hxii** [comment]
Created a PR.

**Pull request closed without merging**
