### PR TITLE
Major enhancements to SimpleStats and HitCounter

### PR DESCRIPTION
**Pull request by BlakesHeaven**
Hello, I would be very pleased if you would take my enhancements into your core product. 

**Current version**
Simple Stats (data collection, Dashboard and separate Hit Counter)
Issues:

- Count goes up on each page refresh
- Collection of data fixed at 7 days needing a code change to alter.

Old Functionality:

- Only collects daily results (fixed 7 days)
- Hit counter only shows the current days hit rate.

**New enhanced version**
Simple Stats (data collection, Dashboard and separate Hit Counter)
Fixed:
- A session for each page is started preventing constant page refreshing artificially increasing the count
- Collection Periods are all parametrised and configurable in settings

New Functionality:

- Enhanced – Daily stats retention now has variable data retention(able to independently turn off)
- New –  Weekly stats captured for x weeks (able to independently turn off)
- New – Monthly stats captured for x months  (able to independently turn off)
- New – Page session with configurable timeout
- New – Running total of all page hits captured
- All existing Languages expanded for all changes plus some added
- Dashboard - Can change the displayed chart type within plugin settings
- New – Dashboard now also shows total page count
- Total Page count can be set via a combination of admin settings and visiting a web page to trigger.
- Enhanced - Hit Counter: sidebar independently displays all current collection data as configured in settings

Not done yet, but want to do

- Display all charts within Tab Navigation without having to change settings
- Individual rolling page count

Images:
image
image
image
image

### CODE REVIEW

**Comment by dignajar** [comment]
Hi, I would like to keep as simple as it is.
You can create a plugin separated, like Simplestats+ or something like you want, don't feel I don't like what you did because for me is really cool, but I want to keep really simple the core then improve it with plugins.

**Comment by BlakesHeaven** [comment]
Hi, that's a shame, especially as it keeps the simplicity of the original very simple stats plugin, but just enhanced. All the enhancementsbcan be turned off if people want it really simple, but it's your decision.
Thanks anyway .

**Comment by DivineDominion** [comment]
@BlakesHeaven did you end up publishing this as an improved plugin?

**Comment by BlakesHeaven** [comment]
Hi @DivineDomination
Yes I did, see https://plugins.bludit.com/plugin/simple-stats-plus

**Comment by BlakesHeaven** [comment]
This pull request is now behind the plugin so I'll close it.

**Pull request closed without merging**
